### ISSUE TITLE
codes does not compile under xcode 7

### ISSUE THREAD

**Issue by wilbyang** [udacity/ios-persistence-2.0#20]
the compile error is:

ios-persistence-2.0/CoreDataFavoriteActors/FavoriteActors/FavoriteActorViewController.swift:212:10: Objective-C method 'controller:didChangeObject:atIndexPath:forChangeType:newIndexPath:' provided by method 'controller(_:didChangeObject:atIndexPath:forChangeType:newIndexPath:)' conflicts with optional requirement method 'controller(_:didChangeObject:atIndexPath:forChangeType:newIndexPath:)' in protocol 'NSFetchedResultsControllerDelegate'

**Comment by saraswatayu** [comment]
Hi @wilbyang 

What branch were you receiving this error on?
